services:
    react:
        image: 'node:20.11.1-slim'
        ports:
            - '3000:3000'
        working_dir: /home/node/app/
        volumes:
            - './Front-End:/home/node/app'
            - '/etc/localtime:/etc/localtime:ro'
        user: '${USER_ID}:${USER_GROUP}'
        command: sh -c 'npm ci && npm run dev -- --host 0.0.0.0'
        restart: always

    go-api:
        image: 'golang:1.23.0-alpine'
        ports:
            - '5000:5000'
        working_dir: /app/
        volumes:
            - './Back-End:/app'
            - '/etc/localtime:/etc/localtime:ro'
            # include this if you want faster container bootup times
            #- '${HOME}/go/pkg/mod:/root/go/pkg/mod'
        command: sh -c 'mkdir -p /.cache && chmod -R 777 /.cache && go run ./cmd/api'
        restart: always
        env_file: './.env'

    nginx:
        image: 'nginx:1.28.0-alpine'
        depends_on:
            - react
            - go-api
        ports:
            - '80:80'
        volumes:
            - '${PWD}/Docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - '${PWD}/Docker/nginx/locations.d/:/etc/nginx/locations.d/'
            - '${PWD}/Front-End/public:/etc/nginx/html'
            - '${PWD}/Front-End/index.html:/etc/nginx/html/index.html'
        restart: always